flowchart TD
    A[<b>Client View</b><br>Input Username] 
    B[<b>Client DAO User</b><br>getUserByUsername]
    C[<b>Servidor</b><br>Webservice]
    D[<b>Server DAO User</b><br>getUserByUsername]
    E[<b>Client View</b><br>Show Info if Exists]
    F[<b>Error Handling</b><br>User Not Found]

    A -->|Envia dades username| B
    B -->|Petición HTTP GET username| C
    C -->|Resposta HTTP amb JSON<br>User if exists| B
    C -->|Consulta DaoUser| D
    D -->|Respond Object User if exists| C
    C -->|User Not Found| F
    B -->|Dades Processades| E
    F -->|Show Error Message| A
