graph LR
    A[Inicio] --> B{Login}
    B --> C[Registro]
    B --> E{Administrador}
    B --> F{Médico}
    B --> G{Tutor}
    B --> H{Usuario}
    G --> I{Un Niño}
    G --> J{Lista de Niños}
    F --> K{Lista de Niños y Tutores}
    E --> L{Modificar Información}
