graph LR
    subgraph Inicio
        A[Inicio]
    end
    subgraph Login
        B{Login}
    end
    subgraph Registro
        C[Registro]
    end
    subgraph RecuperarContraseña
        D{Recuperar Contraseña}
    end
    subgraph Administrador
        E{Administrador}
    end
    subgraph Médico
        F{Médico}
    end
    subgraph Tutor
        G{Tutor}
    end
    subgraph Niño
        H{Un Niño}
    end
    subgraph ListasMédico
        I{Lista de Niños}
        J{Lista de Tutores}
        K{Lista de Cuidadores}
        L{Añadir Cuidadores}
    end
    subgraph ModificarInformación
        M{Modificar Información}
    end
    subgraph ListaUsuarios
        N{Lista de Usuarios}
    end
    subgraph ModificarUsuario
        O{Modificar Usuario}
    end

    A --> B
    B --> C
    B --> D
    C --> B
    D --> B
    B --> E
    B --> F
    B --> G
    F --> H
    G --> H
    F --> I
    F --> J
    F --> K
    K --> L
    E --> M
    M --> N
    N --> O
