flowchart TD
    A[<b>Client View</b> <br> Input username] -->|Envia dades username| B[Client DAO User<br> getUserByUsername]
    B -->|Petición HTTP GET username| C[<b>Servidor</b> <br> Webservice]
    C -->|Resposta HTTP amb JSON<br>user if exist| B
    C -->|Consulta DaoUser| D[Server DAO User<br> getUserByUsername]
    D -->|Respond Object User if exits| C
    B -->|Dades Procesades| E[Client View show info if exits]
