graph LR
    subgraph Inicio
        A[Inicio]
    end
    subgraph Login
        B{Login}
    end
    subgraph Registro
        C[Registro]
    end
    subgraph RecuperarContraseña
        D{Recuperar Contraseña}
    end
    subgraph Administrador
        E{Administrador}
    end
    subgraph Médico
        F{Médico}
    end
    subgraph Tutor
        G{Tutor}
    end
    subgraph Niño
        H{Un Niño}
        I{Lista de Niños}
    end
    subgraph ListasMédico
        J{Lista de Cuidadores}
        K{Añadir Cuidadores}
    end
    subgraph ModificarInformación
        L{Modificar Información}
    end
    subgraph ListaUsuarios
        M{Lista de Usuarios}
    end
    subgraph ModificarUsuario
        N{Modificar Usuario}
    end

    A --> B
    B --> C
    B --> D
    C --> B
    D --> B
    B --> E
    B --> F
    B --> G
    F --> H
    G --> H
    G --> I
    F --> J
    J --> K
    E --> L
    L --> M
    M --> N
