graph LR
    subgraph Inicio
        A[Inicio]
    end
    subgraph Login
        B{Login<br>Usuario y Contraseña}
    end
    subgraph Registro
        C[Registro<br>Nombre, Apellido, Email, Contraseña]
        E{Añadir Niño}
    end
    subgraph RecuperarContraseña
        F{Recuperar Contraseña<br>Email}
    end
    subgraph Usuario
        G{Usuario<br>Nombre, Apellido, Email}
        H{Lista de Niños<br>Nombre, Edad, Fecha de Nacimiento}
        I{Ver Niños<br>Nombre, Edad, Fecha de Nacimiento, Información Médica}
    end
    subgraph Perfil
        J{Ver Perfil<br>Nombre, Apellido, Email, Información Personal}
        L{Añadir Niño}
    end
    subgraph Niño
        K{Historial de Parches<br>Fecha, Hora, Estado, Recuento de horas}
    end

    A --> B
    B --> C
    C --> E
    E --> C
    B --> F
    F --> B
    B --> G
    G --> J
    G --> H
    H --> I
    I --> K
    J --> L
    L --> J
