graph LR
    subgraph Inicio
        A[Inicio]
    end
    subgraph Login
        B{Login<br>Usuario y Contraseña}
    end
    subgraph Registro
        C[Registro<br>Nombre, Apellido, Email, Contraseña<br>Nombre del Niño, Edad del Niño, Fecha de Nacimiento del Niño]
    end
    subgraph RecuperarContraseña
        D{Recuperar Contraseña<br>Email}
    end
    subgraph Perfil
        F{Ver Perfil<br>Nombre, Apellido, Email, Información Personal}
    end
    subgraph Niño
        I{Lista de Niños<br>Nombre, Edad, Fecha de Nacimiento}
        G{Ver Niños<br>Nombre, Edad, Fecha de Nacimiento, Información Médica}
    end
    subgraph Añadir Niño
        H{Añadir Niño<br>Nombre, Edad, Fecha de Nacimiento}
    end

    A --> B
    B --> C
    B --> D
    C --> B
    D --> B
    C --> H
    H --> I
    I --> G
    G --> H
    I --> F
