classDiagram
    class RelationUserChild {
        -int id
        -int id_rol
        -String username
        -String email
        -String contrasenya
    }

    class RelationUserChild {
        -int id
        -int id_child
        -int id_user
        -int id_status
        -datetime init
        -datetime end
    }

    class Rol {
        -int id
        -String type_rol
    }

    class Child {
        -int id
        -String Child_name
        -int sleep_average
        -int treatament_id
        -int time
    }

    class Status {
        -int id
        -String name
    }

    class Treatament {
        -int id
        -String name
    }

    class URelationUserChild {
        -int id_child
        -int id_rol
        -int id_user
    }
