classDiagram
    class Inicio {
        +Inicio()
    }

    class Login {
        +Login(usuario: String, contraseña: String)
    }

    class RecuperarContraseña {
        +RecuperarContraseña(email: String)
    }

    class Registro {
        +Registro(nombre: String, apellido: String, email: String, contraseña: String)
        +AñadirNiño(nombreNiño: String, edadNiño: Int, fechaNacimiento: Date, informaciónMédica: String)
    }

    class Usuario {
        +Nombre: String
        +Apellido: String
        +Email: String
        +ListaDeNiños: List~Niño~
        +VerNiños()
    }

    class Perfil {
        +VerPerfil()
        +AñadirNiño(nombreNiño: String, edadNiño: Int, fechaNacimiento: Date, informaciónMédica: String)
    }

    class Niño {
        +Nombre: String
        +Edad: Int
        +FechaNacimiento: Date
        +InformaciónMédica: String
        +HistorialDeParches: List~Parche~
    }

    class Parche {
        +Fecha: Date
        +Hora: Time
        +Estado: String
        +RecuentoDeHoras: Int
    }

    Inicio --> Login
    Login --> Registro
    Login --> RecuperarContraseña
    Registro --> Usuario
    Usuario --> Perfil
    Usuario --> Niño
    Niño --> Parche
    Perfil --> Niño
