graph TD
    A[Usuario] --> B[UsuarioDAO]
    B --> C[API: /login]
    B --> D[API: /registro]
    A --> E[ViewConsole]
    E --> F[Get Input]
    F --> B

    G[Nen] --> H[NenDAO]
    H --> I[API: /children/{child_name}]
    G --> J[HistorialTapat]
    J --> K[LlistaHistorial]
    K --> L[API: /historial/{child_name}]
    G --> E

    subgraph Endpoints
        C[API: /login]
        D[API: /registro]
        I[API: /children/{child_name}]
        L[API: /historial/{child_name}]
    end

    E --> F
    F --> B
    H --> I
    K --> L
